# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffa73b5c5ef8c7bdfa7815ffd0c130cd260d1f765457219c14d1a3c33b8cdc25c6b6348045276e8ba942ec1712d13596f042a28513068a928211442d8d104070

test:
  secret_key_base: 2958722a4c9aea918c78e8a656c0955d390da5746c65da75d4a603189fa2cff3c2f9ad819b887a203aacde2b761b791a516c83a5c47dd7d74b32eac08be3f3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
